// ════════════════════════════════════════════════════════════════
//  HOLODECK ADAPTER
//  Maps the Builder's internal state into the rich config shape the
//  polished /demo template expects (`window.HOLODECK_CONFIG`).
//
//  THE TWO RENDER PATHS — IMPORTANT
//  ─────────────────────────────────
//  Builder UI    → preview-renderer.js  (lightweight thumbnails — Step 7 only)
//  Final export  → /demo template files (polished customer-facing demo)
//
//  The builder previews are NOT the final output. They are indicative
//  cards. The final ZIP ships a copy of the /demo template — the same
//  HTML, CSS, JS, animations, device frames, deck navigation, and
//  premium visual hierarchy the customer-facing Holodeck has.
//
//  This adapter is the bridge. It takes the SE's inputs (customer
//  details, story foundations, story acts, personas, CX components)
//  and produces a complete HOLODECK_CONFIG that drives the polished
//  template without manual editing.
//
//  Public API:
//    HOLO_ADAPTER.toPolishedHolodeckConfig(state)
//        → object matching /demo/holodeck.config.js shape
//    HOLO_ADAPTER.toPolishedHolodeckConfigJs(state)
//        → string: "window.HOLODECK_CONFIG = {...};"
//
//  When fields are missing (Zone-2 content the SE didn't provide),
//  the adapter inserts clearly-marked "[TODO: ...]" placeholders so
//  the SE knows what to fill in before going live.
// ════════════════════════════════════════════════════════════════

(function (global) {
  "use strict";

  const TODO = "[TODO: confirm with customer]";

  // ─── Asset library lookup ────────────────────────────────────
  // Step 7's "Assets" panel writes uploads (data URLs) into
  // state.assetLibrary keyed by slot name. The adapter looks up
  // each slot here so anything the SE uploaded flows into the
  // exported config. Slots without an upload fall back to the
  // legacy empty-string default — same as before this feature.
  function asset(state, slot) {
    const lib = (state && state.assetLibrary) || {};
    const v = lib[slot];
    return (typeof v === "string" && v) ? v : "";
  }

  // ─── Public entry ────────────────────────────────────────────
  function toPolishedHolodeckConfig(state) {
    state = state || {};
    const project = state.project || {};
    const brand   = state.brand   || {};
    const f       = state.storyFoundations || {};
    const personas = state.personas || [];
    const persona  = personas[0] || null;
    const acts     = state.storyActs || [];
    const products = (project.products || []);

    return {
      customer:          buildCustomer(state, project, f),
      presenter:         buildPresenter(project),
      brand:             buildBrand(brand),
      scenes:            buildScenes(state),
      deckOutline:       buildDeckOutline(state),
      bvs:               buildBvs(state, f),
      persona:           buildPersona(persona, project, state),
      journey:           buildJourney(state, f, products, acts),
      customer_narrative: buildCustomerNarrative(project, f),
      demoStructure:     buildDemoStructure(state, f),
      vignetteSections:  buildVignetteSections(state, f),
      slides:            buildSlidesStub(state, acts, persona),
      mcpStates:         buildMcpStates(),
      technologies:      buildTechnologies(state, products),
      orbitNodes:        buildOrbitNodes(state, products),
      orbitCenter:       buildOrbitCenter(project),
      orbitCopy:         buildOrbitCopy(state, f, products),
      timeline:          buildTimeline(state, f, acts),
      demoAssets:        buildDemoAssets(state),
      demoSlideText:     buildDemoSlideText(state, persona, project, f),
      openItems:         buildOpenItems(state),

      // ── Builder context, kept around for re-import & for Claude
      //    if the SE wants to enrich Zone 2 further with AI ───
      builderPlan:       buildBuilderPlan(state),
    };
  }

  function toPolishedHolodeckConfigJs(state) {
    const cfg = toPolishedHolodeckConfig(state);
    const banner = [
      "// ════════════════════════════════════════════════════════════════",
      "//  HOLODECK CONFIG — generated by the Holodeck Builder",
      "//  Generated: " + new Date().toISOString(),
      "//",
      "//  This file is loaded by /demo/demo-holodeck-unified.html and",
      "//  drives the polished customer-facing Holodeck.",
      "//",
      "//  Anything tagged [TODO: ...] is a placeholder the SE should",
      "//  replace before presenting externally.",
      "// ════════════════════════════════════════════════════════════════",
      "",
      "window.HOLODECK_CONFIG = " + stringifyJs(cfg, 2) + ";",
      "",
    ].join("\n");
    return banner;
  }

  // ─── customer ────────────────────────────────────────────────
  function buildCustomer(state, project, f) {
    const name        = project.customerName || "Customer";
    const nameDisplay = (project.customerName || "CUSTOMER").toUpperCase();
    const theme       = project.theme || "Salesforce Customer Experience Vision";
    return {
      name:           name,
      nameDisplay:    nameDisplay,
      website:        project.website || "",
      industry:       project.industry || "",
      demoTitle:      theme,
      demoSubtitle:   sub2(project, f),
      journeyTagline: titleTagline(products(project), f),
      // Hero headline must be SHORT — these slots are display-type
      // (60+ pt). Long paragraphs overflow. We keep the long prose
      // for the sub fields below.
      heroHeadline:   shortHeroHeadline(name, project, f),
      heroSub:        heroSubLine(name, project, f),
      storyHook:      shortStoryHook(name, f),
      storyHookSub:   storyHookSub(f, name),
      closingQuote:   shortClosingQuote(f),
    };
  }
  function products(p) { return (p && p.products) || []; }
  function sub2(project, f) {
    if (project.theme) return project.theme;
    if (project.industry) return project.industry + " · " + (project.audience || "Executive") + " story";
    return "Connected customer experience";
  }
  function titleTagline(prods, f) {
    const verbs = ["PERSONALIZED", "AGENTIC", "CONNECTED"];
    if (prods.indexOf("Loyalty") >= 0) verbs.push("LOYAL");
    return verbs.slice(0, 3).join(" • ");
  }

  // ─── Short, display-type headline copy ───────────────────────
  // Templates render hero/story headlines at 60-80pt with em accents.
  // Long script paragraphs overflow these slots. We synthesize a
  // crisp headline from the customer name + a one-word stance, and
  // let the long prose live in the sub-headline.
  function shortHeroHeadline(name, project, f) {
    const stance = pickStance(f);
    // "<Customer>,<br/>reimagined as one <em>agentic</em> journey."
    return name + ",<br/>" + stance.before + " <em>" + stance.accent + "</em> " + stance.after + ".";
  }
  function pickStance(f) {
    // Bias the language toward whatever the script emphasized.
    if (f.agentforceMoments && f.agentforceMoments.length) {
      return { before: "reimagined as one", accent: "agentic", after: "journey" };
    }
    if (f.dataCloudMoments && f.dataCloudMoments.length) {
      return { before: "powered by a", accent: "unified", after: "customer profile" };
    }
    if (f.commerceMoments && f.commerceMoments.length) {
      return { before: "a", accent: "personalized", after: "shopper journey" };
    }
    return { before: "a", accent: "connected", after: "customer journey" };
  }
  function heroSubLine(name, project, f) {
    return name + " + Salesforce";
  }
  function shortStoryHook(name, f) {
    // Always synthesize a short, display-type hook. The long script
    // text is too dense for this 60-pt slot. The full story copy
    // lives in storyHookSub (smaller body type).
    if (f.agentforceMoments && f.agentforceMoments.length) {
      return "From a single signal<br/>to an <em>agentic</em> journey.";
    }
    if (f.dataCloudMoments && f.dataCloudMoments.length) {
      return "From scattered signals<br/>to a <em>unified</em> profile.";
    }
    if (f.commerceMoments && f.commerceMoments.length) {
      return "From browse to buy,<br/><em>personalized</em> end to end.";
    }
    return "From a single moment<br/>to a <em>lifetime</em> of relevance.";
  }
  function storyHookSub(f, name) {
    // This IS the long-prose slot, so use the full business problem.
    if (f.businessProblem) return truncate(f.businessProblem, 280);
    if (f.primaryNarrative) return truncate(f.primaryNarrative, 280);
    return "Every interaction builds context. Every context makes the next experience more personal.";
  }
  function shortClosingQuote(f) {
    if (f.executiveTakeaway) return oneSentence(f.executiveTakeaway, 120) || truncate(f.executiveTakeaway, 120);
    return TODO + " — closing one-line takeaway";
  }
  // Pick the first sentence and truncate. Returns "" if no good fit.
  function oneSentence(s, max) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    if (!s) return "";
    const m = s.match(/^[^.!?]+[.!?]/);
    let out = m ? m[0].trim() : s;
    if (out.length > max) out = out.slice(0, max - 1).replace(/\s+\S*$/, "") + "…";
    return out;
  }
  function cleanHeadline(s, max) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    if (s.length > max) s = s.slice(0, max - 1).replace(/\s+\S*$/, "") + "…";
    return s;
  }

  // ─── presenter / brand ───────────────────────────────────────
  function buildPresenter(project) {
    return {
      name:    project.presenterName  || "[PRESENTER NAME]",
      title:   project.presenterTitle || "[TITLE]",
      company: "Salesforce",
    };
  }
  function buildBrand(b) {
    return {
      logoPath:       b.logoPath || null,
      primaryColor:   b.primaryColor   || "#b22234",
      secondaryColor: b.secondaryColor || "#1a5fa0",
      accentColor:    b.accentColor    || "#f5c06a",
      navyColor:      "#0d1b2e",
      bgColor:        "#f5f7ff",
      fontHeading:    "'Playfair Display', Georgia, serif",
      fontBody:       "'Inter', -apple-system, sans-serif",
      googleFontsUrl: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;1,400;1,600&family=Inter:wght@300;400;500;600;700;800&display=swap",
    };
  }

  // ─── scenes (CX component links → /demo's scenes shape) ──────
  // /demo expects scenes as an OBJECT keyed by id (instagramAd, agenticSms,
  // shopperAgent) used directly in the HTML (#scene-instagram .src etc.).
  // We provide both shapes: the legacy array (for builder round-trip) and
  // the keyed object the polished template reads.
  function buildScenes(state) {
    const cx = state.cxComponents || [];
    // The polished template references three named iframes:
    //   #scene-instagram, #scene-sms, #scene-shopper
    // Map by component type / id heuristics.
    const out = { instagramAd: "", agenticSms: "", shopperAgent: "" };
    cx.forEach(function (c) {
      const k = String(c.id || "").toLowerCase();
      const t = String(c.type || "").toLowerCase();
      const n = String(c.name || "").toLowerCase();
      if (/instagram|paid|ad/.test(k + n) || t === "marketing" && /ad|paid/.test(n)) {
        if (!out.instagramAd) out.instagramAd = c.url || "";
      } else if (/sms|text|message/.test(k + n) || (t === "marketing" && c.deviceFrame === "mobile")) {
        if (!out.agenticSms) out.agenticSms = c.url || "";
      } else if (/agent|shopper|chat/.test(k + n) || t === "agent" || t === "commerce") {
        if (!out.shopperAgent) out.shopperAgent = c.url || "";
      }
    });
    // Fill any gap with the next available CX URL so the template
    // doesn't load empty iframes.
    cx.forEach(function (c) {
      if (!out.instagramAd  && c.url) out.instagramAd  = c.url;
      else if (!out.agenticSms   && c.url) out.agenticSms   = c.url;
      else if (!out.shopperAgent && c.url) out.shopperAgent = c.url;
    });
    // Empty strings for un-linked scene slots (rather than literal
    // [TODO:] paths) so iframes don't try to load a bogus URL — they
    // simply stay blank with the device frame visible. SE replaces
    // these with real /frame URLs in holodeck.config.js after export.
    if (!out.instagramAd)  out.instagramAd  = "about:blank";
    if (!out.agenticSms)   out.agenticSms   = "about:blank";
    if (!out.shopperAgent) out.shopperAgent = "about:blank";
    return out;
  }

  // ─── deckOutline (legacy Holodeck slide-types ordering) ─────
  function buildDeckOutline(state) {
    const layoutToType = (global.HOLO_RULES && global.HOLO_RULES.LAYOUT_TO_SLIDE_TYPE) || {};
    const linkedSlideIds = explicitlyLinkedSlideIds(state);
    return (state.slides || []).map(function (s) {
      // Same promotion as buildBuilderPlan — explicit CX link forces
      // an embedded layout regardless of the saved slide.layout.
      const layout = linkedSlideIds[s.id] ? "embeddedCxComponent" : s.layout;
      const type = layoutToType[layout] || "two-panel";
      const note = s.title + (s.speakerNotes ? " — " + s.speakerNotes : "");
      return { type: type, note: note };
    });
  }
  function explicitlyLinkedSlideIds(state) {
    const out = {};
    (state.cxComponents || []).forEach(function (c) {
      const sid = (c.linkedSlideIds && c.linkedSlideIds[0]) || "";
      if (sid) out[sid] = true;
    });
    return out;
  }

  // ─── bvs ─────────────────────────────────────────────────────
  function buildBvs(state, f) {
    const drivers = (f.valueDrivers || []).slice(0, 5);
    const metrics = drivers.length
      ? drivers.map(function (d, i) {
          const icons = ["↑", "💳", "★", "🔄", "⚡"];
          return { icon: icons[i] || "→", value: "[TODO: %]", label: shortenLabel(d) };
        })
      : [
          { icon: "↑",  value: "XX%",  label: "Conversion Lift" },
          { icon: "💳", value: "+$XX", label: "Average Order Value" },
          { icon: "★",  value: "XX%",  label: "Loyalty Enrollment" },
          { icon: "🔄", value: "XXx",  label: "Repeat Purchase Rate" },
          { icon: "⚡", value: "XX%",  label: "Service Efficiency" },
        ];
    return {
      disclaimer: "Replace placeholders with BVS-approved values before presenting externally.",
      metrics: metrics,
    };
  }
  function shortenLabel(s) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    // Trim "Higher conversion through ..." → "Conversion Lift"
    const m = s.match(/^(?:higher|increased|improved|reduced|faster)\s+([\w\s\/]+?)(\s+through|\s+via|\s+from|$)/i);
    if (m) return titleCase(m[1].trim());
    return titleCase(s.split(/[.;]/)[0].slice(0, 32));
  }
  function titleCase(s) {
    return String(s || "").replace(/\b\w/g, function (c) { return c.toUpperCase(); });
  }

  // ─── persona ─────────────────────────────────────────────────
  function buildPersona(p, project, state) {
    if (!p) {
      return {
        name:        "[TODO: persona first name]",
        fullName:    "[TODO: persona full name]",
        role:        "[TODO: persona role]",
        jobTitle:    "[TODO: persona job title]",
        customerOf:  project.customerName || "[Customer Name]",
        journeyArc:  "[TODO: one-line journey arc]",
        quote:       "[TODO: persona quote in their own voice]",
        stats:       defaultPersonaStats(),
        wishlist:    defaultPersonaWishlist(),
        wishlistHeadline: "[TODO: wishlist headline]",
        wishlistLabel:    "[TODO: wishlist section label]",
        ctaLabel:         "BEGIN THE JOURNEY &nbsp;→",
        ctaHeadline:      "[TODO: closing CTA headline]",
        ctaSub:           "[TODO: closing CTA sub]",
        heroBackground:   asset(state, "persona.heroBackground"),
        heroGif:          asset(state, "persona.heroGif"),
        phoneGif:         asset(state, "persona.phoneGif"),
        portrait:         asset(state, "persona.portrait"),
      };
    }
    const first = (p.name || "").trim().split(/\s+/)[0] || "[TODO: persona]";
    const full  = p.name || "[TODO: persona full name]";
    return {
      name:        first,
      fullName:    full,
      role:        p.role || "[TODO: persona role]",
      jobTitle:    p.role || "[TODO: persona job title]",
      customerOf:  project.customerName || "",
      journeyArc:  truncate(p.demoRelevance || p.goals || "[TODO: one-line journey arc]", 110),
      quote:       p.painPoints
                     ? cleanQuote(p.painPoints)
                     : (p.goals ? cleanQuote(p.goals) : "[TODO: persona quote]"),
      stats:       defaultPersonaStats(),
      wishlist:    defaultPersonaWishlist(),
      wishlistHeadline: "Her top 3. <strong>Picked just for her.</strong>",
      wishlistLabel:    first + "'s Wishlist",
      ctaLabel:         "BEGIN THE JOURNEY &nbsp;→",
      ctaHeadline:      "Let's follow " + first + "'s journey.",
      ctaSub:           truncate(p.demoRelevance || "From inspiration to purchase to loyalty.", 110),
      // Empty strings (not literal "[TODO:]" paths) so the browser
      // skips fetching a broken image. Step 7's Assets panel writes
      // any uploads into state.assetLibrary, which we read here so
      // the SE doesn't have to drop files into demo/assets/ post-export.
      heroBackground:   asset(state, "persona.heroBackground"),
      heroGif:          asset(state, "persona.heroGif"),
      phoneGif:         asset(state, "persona.phoneGif"),
      portrait:         asset(state, "persona.portrait"),
    };
  }
  function defaultPersonaStats() {
    return [
      { value: "[TODO]", label: "Top Moment"   },
      { value: "[TODO]", label: "Tradition"    },
      { value: "[TODO]", label: "Signal"       },
    ];
  }
  function defaultPersonaWishlist() {
    return [
      { name: "[TODO: top product]",    tag: "PRIMARY CONSIDERATION", detail: "[TODO]", emoji: "🛍️" },
      { name: "[TODO: companion]",      tag: "AI MATCH",              detail: "[TODO]", emoji: "✨" },
      { name: "[TODO: complete-the-look]", tag: "COMPLETE THE LOOK",  detail: "[TODO]", emoji: "🎁" },
    ];
  }
  function cleanQuote(s) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    if (!s) return "";
    if (s.length > 140) s = s.slice(0, 137).replace(/\s+\S*$/, "") + "…";
    return s;
  }

  // ─── journey (Section A: Journey Map circles) ───────────────
  // /demo expects 5 circle-classes: anticipate, engage, guide, convert, delight.
  // We map storyActs into 5 buckets (or pad with sensible defaults).
  function buildJourney(state, f, prods, acts) {
    const headline = f.transformationThesis
      ? cleanHeadline(f.transformationThesis, 70)
      : "A <strong>connected journey</strong>";
    const steps = bucketActsIntoFive(acts, prods);
    return {
      headline: headline,
      steps:    steps,
      platform: {
        title:    "Salesforce Platform",
        subtitle: prods.map(function (p) { return p.toUpperCase(); }).join(" · ") || "AGENTFORCE · DATA CLOUD · COMMERCE",
        capabilities: prods.length ? prods : ["Agentforce", "Data Cloud", "Commerce", "Marketing Cloud"],
      },
    };
  }
  // Heuristic: take 5 highlights from acts. If fewer than 5, pad with
  // generic phase headers tied to the product mix.
  function bucketActsIntoFive(acts, prods) {
    const circleClasses = ["circle-anticipate", "circle-engage", "circle-guide", "circle-convert", "circle-delight"];
    const phaseTitles   = ["Know", "Reach", "Engage", "Recover", "Convert"];
    const emojis        = ["🏪", "📸", "🛍️", "💬", "🤖"];
    // Filter out chapter-header rows (titles like "Intro" / "Open" /
    // "Close") so the 5 circles show real moments, not section titles.
    function isHeaderTitle(t) { return !t || /^(intro|opening|open|chapter\s|section\s|close|closing)/i.test(t); }
    const milestones = acts.filter(function (a) { return a && a.summary && !isHeaderTitle(a.title); });
    const out = [];
    for (let i = 0; i < 5; i++) {
      const a = milestones[i];
      out.push({
        title:        a && a.title ? shortenTitle(a.title) : phaseTitles[i],
        badge:        a && a.salesforceCapabilities ? truncate(a.salesforceCapabilities, 36) : (prods[i] || "Salesforce"),
        emoji:        emojis[i],
        circleClass:  circleClasses[i],
        description:  a && a.summary ? truncate(a.summary, 200) : phaseDescription(phaseTitles[i], prods),
        detail:       a && (a.notes || a.summary) ? truncate((a.notes || "") + " " + (a.summary || ""), 280) : phaseDetail(phaseTitles[i]),
        technologies: a && a.salesforceCapabilities
          ? a.salesforceCapabilities.split(/[,/·•]/).map(function (s) { return s.trim(); }).filter(Boolean)
          : (prods.slice(0, 2).length ? prods.slice(0, 2) : ["Data Cloud"]),
      });
    }
    return out;
  }
  function phaseDescription(t, prods) {
    return ({
      "Know":    "Identity captured; the journey begins from a single moment.",
      "Reach":   "Targeted, personalized outreach finds the customer where they already are.",
      "Engage":  "Personalized content adapts to the customer's intent in real time.",
      "Recover": "Proactive re-engagement turns a near-miss into a relationship.",
      "Convert": "An agentic moment closes the loop — purchase, service, or loyalty.",
    })[t] || "Salesforce powers a connected moment.";
  }
  function phaseDetail(t) {
    return phaseDescription(t) + " [TODO: enrich with customer-specific detail]";
  }
  function shortenTitle(s) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    if (s.length > 22) s = s.slice(0, 22).replace(/\s+\S*$/, "");
    return s;
  }

  // ─── customer_narrative (Intro deck + closing) ──────────────
  function buildCustomerNarrative(project, f) {
    const theme = project.theme || "Salesforce Customer Experience Vision";
    return {
      demoTitle:      theme,
      demoSubtitle:   project.industry ? (project.industry + " journey") : "Connected customer journey",
      journeyTagline: "PERSONALIZED • AGENTIC • CONNECTED",
      heroHeadline:   f.futureStateVision
        ? cleanHeadline(f.futureStateVision, 100)
        : "A connected, <em>agentic</em><br/>customer journey.",
      heroSub:        (project.customerName || "Customer") + " + Salesforce",
      storyHook:      f.primaryNarrative
        ? cleanHeadline(f.primaryNarrative, 100)
        : "See how a single moment becomes a connected journey.",
      storyHookSub:   f.businessProblem
        ? truncate(f.businessProblem, 240)
        : "Every interaction builds context. Every context makes the next experience more personal.",
      closingQuote:   f.executiveTakeaway || "[TODO: closing executive quote]",
    };
  }

  // ─── demoStructure (Intro three-act breakdown) ─────────────
  function buildDemoStructure(state, f) {
    return [
      {
        title:       "Know & Reach",
        description: f.dataCloudMoments && f.dataCloudMoments.length
          ? truncate(f.dataCloudMoments[0], 200)
          : "Data Cloud unifies the customer's signals across channels — a foundation for every downstream moment.",
        tags:        deriveTags(f, "intro"),
      },
      {
        title:       "Engage & Recover",
        description: (f.commerceMoments && f.commerceMoments[0]) || (f.marketingMoments && f.marketingMoments[0]) || "Personalized engagement adapts to the customer's intent in real time. Proactive re-engagement closes near-misses.",
        tags:        deriveTags(f, "demo"),
      },
      {
        title:       "Convert",
        description: (f.agentforceMoments && f.agentforceMoments[0]) || (f.serviceMoments && f.serviceMoments[0]) || "An agentic moment closes the loop with the customer.",
        tags:        deriveTags(f, "close"),
      },
    ];
  }
  function deriveTags(f, stage) {
    if (stage === "intro") return ["Data Cloud", "Email", "Paid Media", "Anonymous → Known"];
    if (stage === "demo")  return ["Commerce", "AI Search", "Agentic SMS", "MCP"];
    return ["Agentforce", "Commerce", "Clicks not code", "GA today"];
  }

  // ─── vignetteSections (Intro chapter slides) ────────────────
  function buildVignetteSections(state, f) {
    return [
      {
        eyebrow:  "DATA CLOUD · MARKETING CLOUD",
        title:    "Know & Reach",
        subtitle: f.dataCloudMoments && f.dataCloudMoments.length
          ? truncate(f.dataCloudMoments[0], 220)
          : "Identity, signals, and segments power every downstream touchpoint.",
      },
      {
        eyebrow:  "COMMERCE · MARKETING CLOUD",
        title:    "Engage & Recover",
        subtitle: f.marketingMoments && f.marketingMoments.length
          ? truncate(f.marketingMoments[0], 220)
          : "Personalized engagement, then proactive recovery when the customer drops off.",
      },
      {
        eyebrow:  "AGENTFORCE",
        title:    "Convert",
        subtitle: f.agentforceMoments && f.agentforceMoments.length
          ? truncate(f.agentforceMoments[0], 220)
          : "One conversation. Full cart. Closed loop. Then post-purchase nurture extends the relationship.",
      },
    ];
  }

  // ─── slides (Demo deck slide payload) ────────────────────────
  // The polished template's Demo section is built around At-Home-style
  // demo slides ("is-1" through "is-14"). Without a Claude pass we
  // can't generate that level of detail. We emit a deckOutline-shaped
  // slides[] so the legacy renderer at least has structure, and we
  // mark with [TODO:] for the SE.
  function buildSlidesStub(state, acts, persona) {
    const slides = state.slides || [];
    if (!slides.length) {
      return [{
        type:     "title",
        eyebrow:  "Open the demo",
        headline: "[TODO: opening slide headline]",
        sub:      "[TODO: opening slide sub]",
      }];
    }
    const linkedSlideIds = explicitlyLinkedSlideIds(state);
    return slides.map(function (sl, i) {
      // Map builder layouts to /demo slide types — promote any
      // explicitly-linked slide to embeddedCxComponent so it renders
      // as an iframe (consistent with buildBuilderPlan above).
      const layout = linkedSlideIds[sl.id] ? "embeddedCxComponent" : sl.layout;
      const type = builderLayoutToHolodeckSlideType(layout);
      const base = {
        type:     type,
        eyebrow:  capitalize(sl.sectionId || "demo").replace("-", " "),
        headline: sl.title || ("Slide " + (i + 1)),
        sub:      sl.speakerNotes || "[TODO: slide narration]",
      };
      if (type === "two-panel") {
        base.left  = { imagePath: "assets/[TODO: " + slug(sl.title) + ".jpg]", tag: sl.title };
        base.right = {
          eyebrow:  base.eyebrow,
          headline: sl.title || "",
          sub:      "[TODO: slide narrative]",
          stats:    [],
          quote:    "",
        };
      }
      if (type === "iframe-phone" || type === "iframe-laptop") {
        base.left = {
          backgroundPath: "assets/[TODO: scene-bg.jpg]",
          iframeSrc:      "{{scenes." + (sl.linkedCxComponentIds && sl.linkedCxComponentIds[0] || "instagramAd") + "}}",
          tag:            sl.title || "",
        };
        base.right = {
          eyebrow:  base.eyebrow,
          headline: sl.title || "",
          sub:      "[TODO: scene narration]",
          stats:    [],
          quote:    "",
        };
      }
      return base;
    });
  }
  function builderLayoutToHolodeckSlideType(layout) {
    return ({
      hero:                "title",
      storyFoundation:     "title",
      currentFutureState:  "two-panel",
      futureState:         "title",
      journeyTimeline:     "timeline",
      demoMap:             "two-panel",
      personaCard:         "two-panel",
      agentConversation:   "iframe-phone",
      unifiedProfile:      "two-panel",
      architecture:        "two-panel",
      deviceMoment:        "iframe-phone",
      embeddedCxComponent: "iframe-laptop",
      kpiScorecard:        "stat-grid",
      executiveSummary:    "title",
      nextSteps:           "title",
    })[layout] || "two-panel";
  }

  // ─── mcpStates (the 3-state click-through on slide is-8) ────
  function buildMcpStates() {
    return [
      { tag: "[TODO: MCP scene 1 tag]",   headline: "[TODO: MCP scene 1 headline]",   sub: "[TODO: MCP scene 1 sub]",   quote: "[TODO]", counter: "1 / 3" },
      { tag: "[TODO: MCP scene 2 tag]",   headline: "[TODO: MCP scene 2 headline]",   sub: "[TODO: MCP scene 2 sub]",   quote: "[TODO]", counter: "2 / 3" },
      { tag: "[TODO: MCP scene 3 tag]",   headline: "[TODO: MCP scene 3 headline]",   sub: "[TODO: MCP scene 3 sub]",   quote: "[TODO]", counter: "3 / 3" },
    ];
  }

  // ─── technologies (BV capabilities slide) ────────────────────
  function buildTechnologies(state, prods) {
    if (!prods.length) {
      return [
        { label: "Data Cloud",                description: "Unified customer data across every channel and signal." },
        { label: "Agentforce",                description: "Conversational AI agents that ground answers in customer context and close the loop." },
        { label: "Commerce",                  description: "Personalized storefront with AI-powered search built in." },
        { label: "Marketing Cloud",           description: "Personalized SMS, email, and journeys triggered by real-time signals." },
      ];
    }
    const desc = {
      "Data Cloud":      "Unified customer data across every channel and signal.",
      "Agentforce":      "Conversational AI agents that ground answers in customer context and close the loop.",
      "Sales Cloud":     "Pipeline, accounts, and deal-team workflows in one platform.",
      "Service Cloud":   "Case management with AI-assisted resolution and proactive service.",
      "Marketing Cloud": "Personalized SMS, email, and journeys triggered by real-time signals.",
      "Commerce":        "Personalized storefront with AI-powered search built in.",
      "Loyalty":         "Tier-based programs that drive repeat purchase and lifetime value.",
      "MuleSoft":        "Integration across systems of record without ripping and replacing.",
      "Tableau":         "Embedded analytics that make every conversation data-grounded.",
    };
    return prods.map(function (p) {
      return { label: p, description: desc[p] || "[TODO: " + p + " value statement]" };
    });
  }

  // ─── orbit (BV section) ──────────────────────────────────────
  function buildOrbitNodes(state, prods) {
    const seedIcons = ["📸", "🔍", "💬", "🤖", "🛒", "📧"];
    const labels    = orbitLabelsFor(prods);
    return labels.slice(0, 6).map(function (label, i) {
      const ring = i < 3 ? 210 : 120;
      const dur  = i < 3 ? 200 : 200;
      const dir  = i < 3 ? 1 : -1;
      return { icon: seedIcons[i] || "•", label: label, r: ring, startDeg: (i * 60) % 360, dur: dur, dir: dir };
    });
  }
  function orbitLabelsFor(prods) {
    const out = [];
    if (prods.indexOf("Marketing Cloud") >= 0) out.push("Personalized Ad");
    if (prods.indexOf("Commerce") >= 0)         out.push("AI-Powered Search");
    if (prods.indexOf("Marketing Cloud") >= 0) out.push("SMS Re-engagement");
    if (prods.indexOf("Agentforce") >= 0)       out.push("Shopper Agent");
    if (prods.indexOf("Commerce") >= 0)         out.push("Commerce");
    if (prods.indexOf("Marketing Cloud") >= 0) out.push("Post-Purchase Email");
    while (out.length < 6) out.push("[TODO]");
    return out;
  }
  function buildOrbitCenter(project) {
    return {
      emoji: emojiForIndustry(project.industry),
      label: (project.customerName || "CUSTOMER").toUpperCase(),
    };
  }
  function emojiForIndustry(industry) {
    return ({
      "Retail":             "🛍️",
      "Consumer Goods":     "🧺",
      "Hospitality":        "🏨",
      "Travel":             "✈️",
      "Financial Services": "🏦",
      "Healthcare":         "⚕️",
    })[industry] || "🏠";
  }
  function buildOrbitCopy(state, f, prods) {
    return {
      eyebrow:  "One Connected Platform",
      headline: "Personalized at every<br/><span class=\"accent\">touchpoint.</span>",
      body:     f.transformationThesis
        ? truncate(f.transformationThesis, 280)
        : "Salesforce connects data, AI, commerce, marketing, and service into one journey. Every signal informs every channel.",
      stats: [
        { val: prods[0] || "Data Cloud",  label: "Foundation"     },
        { val: prods[1] || "Agentforce",  label: "Agentic moments"},
        { val: prods[2] || "Commerce",    label: "Conversion"     },
      ],
    };
  }

  // ─── timeline (Demo section is-3 horizontal timeline) ───────
  function buildTimeline(state, f, acts) {
    // Skip "chapter header" acts (titles like "Intro" / "Opening" /
    // "Chapter 1") so the timeline shows real journey milestones.
    function isHeaderTitle(t) { return !t || /^(intro|opening|open|chapter\s|section\s|close|closing)/i.test(t); }
    const milestones = acts.filter(function (a) {
      return a && a.summary && !isHeaderTitle(a.title);
    });
    return {
      eyebrow:  "Salesforce · " + ((state.project && state.project.industry) || "Customer Journey"),
      headline: "One journey. Every channel.<br/><span class=\"accent\">Always personal.</span>",
      sub:      f.primaryNarrative
        ? truncate(f.primaryNarrative, 260)
        : "From a single moment, every downstream interaction is connected and personal.",
      above:    milestones.slice(0, 3).map(function (a, i) {
        return { month: pickMonth(i, "above"), icon: pickIcon(a.channel, "above"), label: shortenTitle(a.title || ("Step " + (i + 1))), sub: truncate(a.summary || "", 60) };
      }),
      below:    milestones.slice(0, 7).map(function (a, i, arr) {
        const hero = i === 0 || i === arr.length - 1;
        return { month: pickMonth(i, "below"), icon: pickIcon(a.channel, "below"), label: shortenTitle(a.title || ("Moment " + (i + 1))), sub: truncate(a.summary || "", 60), hero: hero };
      }),
    };
  }
  function pickMonth(i, _row) {
    return ["DEC", "FEB", "APR", "JUN", "JUL", "AUG", "SEP"][i] || "—";
  }
  function pickIcon(channel, _row) {
    if (!channel) return "📱";
    const c = String(channel).toLowerCase();
    if (/store|in[-\s]?store/.test(c)) return "🏪";
    if (/instagram|facebook|paid|ad/.test(c)) return "📸";
    if (/sms|text/.test(c)) return "💬";
    if (/email/.test(c)) return "📧";
    if (/web|site|storefront/.test(c)) return "🖥️";
    if (/imessage|whatsapp/.test(c)) return "💬";
    if (/agent|chat/.test(c)) return "🤖";
    if (/laptop|macbook/.test(c)) return "💻";
    return "📱";
  }

  // ─── demoSlideText (Demo section is-1 + is-2 inline copy) ──
  // The polished template hard-references C.demoSlideText.s1 and
  // C.demoSlideText.s2 in its inline populate script. Without this
  // block the script throws (Cannot read properties of undefined)
  // and the whole demo stops rendering. We emit safe defaults.
  function buildDemoSlideText(state, persona, project, f) {
    const customer = (project.customerName || "Customer");
    const personaName = persona && persona.name ? persona.name.split(/\s+/)[0] : "the customer";
    // First story act with concrete content (skip generic chapter
    // headers like "Intro" / "Open" that don't read as slide copy)
    const acts = (state.storyActs || []);
    function isGenericTitle(t) { return !t || /^(intro|opening|open|chapter\s|section\s)/i.test(t); }
    const firstAct  = acts.find(function (a) { return a && a.summary && !isGenericTitle(a.title); }) || acts[0] || null;
    const secondAct = acts.slice(acts.indexOf(firstAct) + 1).find(function (a) { return a && a.summary; }) || null;

    return {
      s1: {
        eyebrow:  project.theme || (project.industry ? project.industry + " · Vision" : "Salesforce Customer Experience"),
        headline: f.primaryNarrative
          ? "Every great experience begins<br/>with <em>a single signal.</em>"
          : "Every relationship begins<br/>with a <em>single moment.</em>",
        sub:      f.businessProblem
          ? truncate(f.businessProblem, 220)
          : (firstAct && firstAct.summary
              ? truncate(firstAct.summary, 220)
              : "Connected data and AI turn each customer touchpoint into the foundation of the next."),
      },
      s2: {
        sceneCaption: firstAct && firstAct.demoMoment
          ? firstAct.demoMoment
          : (firstAct && firstAct.title && !isGenericTitle(firstAct.title) ? firstAct.title : (firstAct && firstAct.channel ? firstAct.channel + " moment" : "Demo moment")),
        role:     persona && persona.role ? persona.role : "Customer",
        name:     personaName + ".",
        sub:      firstAct && firstAct.summary
          ? truncate(firstAct.summary, 200)
          : (f.businessProblem ? truncate(f.businessProblem, 200) : "The demo opens here."),
        items:    [
          {
            icon:  "🛍️",
            label: "MOMENT",
            text:  firstAct && firstAct.title && !isGenericTitle(firstAct.title) ? firstAct.title : "Discover",
            sub:   firstAct && firstAct.salesforceCapabilities
              ? firstAct.salesforceCapabilities
              : (project.products && project.products[0] ? project.products[0] : "Salesforce"),
          },
          {
            icon:  "📍",
            label: "CHANNEL",
            text:  firstAct && firstAct.channel ? firstAct.channel : "Multi-channel",
            sub:   secondAct && secondAct.channel ? "Then: " + secondAct.channel : "Across the journey",
          },
          {
            icon:  "→",
            label: "OUTCOME",
            text:  firstAct && firstAct.businessValue ? firstAct.businessValue : "Anonymous → Known",
            sub:   "First profile signal in " + customer + "'s data foundation.",
          },
        ],
      },
    };
  }

  // ─── demoAssets (image paths used across slides) ─────────────
  // We deliberately emit empty strings (not "assets/[TODO:…]") for
  // assets the SE hasn't provided yet.  The unified template's
  // populateFromConfig sets .src on these <img> elements; an empty
  // string keeps the browser from rendering the broken-image icon
  // and lets the slide's gradient background show through cleanly.
  // The SE still sees the gap (it's flagged in ASSET_INSTRUCTIONS.md
  // and on the Builder side); but the polished demo doesn't look
  // broken.  Device-frame PNGs (which we *do* ship) keep their paths.
  function buildDemoAssets(state) {
    return {
      storeExterior:     asset(state, "storeExterior"),
      storeInterior:     asset(state, "storeInterior"),
      productHero:       asset(state, "productHero"),
      iPhoneRec:         asset(state, "iPhoneRec"),
      webBrowseGif:      asset(state, "webBrowseGif"),
      laptopBrowsingGif: asset(state, "laptopBrowsingGif"),
      macbookFrame:      "assets/macbook-transparent.png",
      iPhoneFrame:       "assets/iPhone16Pro_FRAME.png",
    };
  }

  // ─── openItems ───────────────────────────────────────────────
  function buildOpenItems(state) {
    const out = [];
    out.push("Update presenter.name and presenter.title");
    out.push("Replace all XX% / +$XX BVS placeholder values with approved benchmarks");
    out.push("Confirm scenes URLs are live and loading in iframes");
    out.push("Add customer logo to assets/ and set brand.logoPath");
    if (!(state.personas || []).length) out.push("Add a persona — at least name, role, and one quote");
    if (!(state.storyActs || []).length) out.push("Outline at least 3 story acts so the journey timeline is rich");
    out.push("Drop persona portrait + product images into assets/ and update demoAssets.* paths");
    return out;
  }

  // ─── builderPlan (round-trip back to the builder) ────────────
  function buildBuilderPlan(state) {
    const project = state.project || {};

    // Build a map of slide.id -> [cxComponentId] from the SE's explicit
    // links. We need this at export time (not just inside the builder's
    // buildSlidePlanFromSelections) so saved projects from before the
    // promotion rule was added still export correctly. The demo runtime
    // ONLY renders an iframe when slide.layout === "embeddedCxComponent",
    // so any explicit link must promote the layout — otherwise the
    // exported config has the link but no iframe slot to put it in.
    const cxAll = state.cxComponents || [];
    const explicitBySlide = {};
    cxAll.forEach(function (c) {
      const sid = (c.linkedSlideIds && c.linkedSlideIds[0]) || "";
      if (sid) {
        explicitBySlide[sid] = explicitBySlide[sid] || [];
        explicitBySlide[sid].push(c.id);
      }
    });

    return {
      audience:   project.audience   || "",
      salesStage: project.salesStage || "",
      products:   project.products   || [],
      tone:       project.tone       || "",
      theme:      project.theme      || "",
      story:            state.story            || {},
      storyFoundations: state.storyFoundations || {},
      personas:         state.personas         || [],
      storyActs:        state.storyActs        || [],
      cxComponents:     cxAll,
      assetLibrary:     state.assetLibrary || {},
      slideSections:    state.slideSections || [],
      slides:           (state.slides || []).map(function (s, i) {
        const explicitCx = explicitBySlide[s.id] || [];
        // Merge: explicit links win, but preserve any pre-existing
        // linkedCxComponentIds (e.g. for native embeddedCxComponent
        // slides whose links were stamped earlier without going
        // through the explicit picker).
        const mergedCx = explicitCx.length
          ? explicitCx
          : (s.linkedCxComponentIds || []);
        const promotedLayout = (explicitCx.length || s.layout === "embeddedCxComponent")
          ? "embeddedCxComponent"
          : s.layout;
        return {
          order: i + 1, id: s.id, title: s.title, layout: promotedLayout,
          sectionId: s.sectionId || "",
          selectionStatus: s.selectionStatus || "",
          selectionRationale: s.selectionRationale || "",
          capabilities: s.capabilities || [],
          persona: s.persona || null,
          linkedCxComponentIds: mergedCx,
          deviceFrame: s.deviceFrame || "",
          speakerNotes: s.speakerNotes || "",
        };
      }),
    };
  }

  // ─── Helpers ─────────────────────────────────────────────────
  function truncate(s, max) {
    s = String(s || "").replace(/\s+/g, " ").trim();
    if (s.length <= max) return s;
    return s.slice(0, max - 1).replace(/\s+\S*$/, "") + "…";
  }
  function slug(s) {
    return String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32) || "item";
  }
  function capitalize(s) { return String(s || "").replace(/^./, function (c) { return c.toUpperCase(); }); }

  // Pretty-printed JS object literal (unquoted identifier keys). Mirrors
  // config-generator.stringifyJs so SEs see a readable file.
  function stringifyJs(value, indent) {
    indent = indent || 2;
    return walk(value, 0);
    function walk(v, depth) {
      if (v === null || v === undefined) return "null";
      const t = typeof v;
      if (t === "string") return JSON.stringify(v);
      if (t === "number" || t === "boolean") return String(v);
      if (Array.isArray(v)) return arr(v, depth);
      if (t === "object") return obj(v, depth);
      return JSON.stringify(v);
    }
    function pad(d) { return " ".repeat(d * indent); }
    function arr(a, depth) {
      if (a.length === 0) return "[]";
      const inner = a.map(function (item) { return pad(depth + 1) + walk(item, depth + 1); }).join(",\n");
      return "[\n" + inner + "\n" + pad(depth) + "]";
    }
    function obj(o, depth) {
      const keys = Object.keys(o);
      if (keys.length === 0) return "{}";
      const inner = keys.map(function (k) {
        const safe = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
        return pad(depth + 1) + safe + ": " + walk(o[k], depth + 1);
      }).join(",\n");
      return "{\n" + inner + ",\n" + pad(depth) + "}";
    }
  }

  global.HOLO_ADAPTER = {
    toPolishedHolodeckConfig: toPolishedHolodeckConfig,
    toPolishedHolodeckConfigJs: toPolishedHolodeckConfigJs,
  };
})(window);
